sudo: false
language: node_js
node_js:
  - 8

dist: trusty # Chrome needs Ubuntu Trusty

addons:
  chrome: stable

before_script:
  - node --version
  - npm --version

script:
  - npm test

matrix:
  fast_finish: true
